---
apiVersion: v1
kind: Namespace
metadata:
  name: policies
spec: {}
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace:  policies
spec:
  clusterSet: global
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: short-name-mode-enforcing
  namespace: policies
spec:
  clusterSets:
    - global
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: short-name-mode-enforcing
  namespace: policies
  annotations:
    policy.open-cluster-management.io/categories: None
    policy.open-cluster-management.io/controls: None
    policy.open-cluster-management.io/standards: short-name-mode-enforcing
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: short-name-mode-enforcing
        spec:
          remediationAction: inform
          severity: medium
          object-templates-raw: >
            {{- range (lookup "v1" "Pod" "" "").items }}
              {{- $podName := .metadata.name }}
              {{- $podNs := .metadata.namespace }}
              {{- range .spec.containers }}
                {{- /* Check if image string lacks a domain (no dot in the first segment) */ -}}
                {{- $imageParts := splitList "/" .image }}
                {{- if not (contains "." (index $imageParts 0)) }}
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  name: {{ $podName }}
                  namespace: {{ $podNs }}
                {{- end }}
              {{- end }}
            {{- end }}
  remediationAction: inform
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: short-name-mode-enforcing
  namespace: policies
placementRef:
  name: short-name-mode-enforcing
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: short-name-mode-enforcing
    kind: Policy
    apiGroup: policy.open-cluster-management.io
